import type { Metadata } from "next";
import { Sora, Manrope } from "next/font/google";
import { LocaleProvider } from "@/lib/i18n";
import "./globals.css";

// Sora (headings) + Manrope (body) — from the UI team's design handoff
// (design-handoff/SkillSync_revisi.html). Loaded at the root so both the
// homepage and every /hr/* page share one font system; see globals.css'
// base layer for how h1-h4 pick up --font-heading.
const sora = Sora({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["500", "600", "700", "800"],
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-body",
  weight: ["400", "500", "600", "700", "800"],
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://skillsync-hackathon.vercel.app";
const TITLE = "Skillsync";
const DESCRIPTION =
  "Where CVs and job needs finally sync. AI-powered CV building for candidates and AI-powered screening & validation for HR recruiters.";

export const metadata: Metadata = {
  // Lets relative URLs elsewhere in the metadata (og:image, canonical, etc.)
  // resolve to an absolute one — without this, a shared link's preview card
  // can silently fail on platforms that require a fully-qualified image URL.
  metadataBase: new URL(SITE_URL),
  title: TITLE,
  description: DESCRIPTION,
  icons: {
    icon: "/favicon.ico",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: SITE_URL,
    siteName: TITLE,
    type: "website",
    // Image itself is auto-generated by app/opengraph-image.tsx — Next.js
    // wires it up automatically, so no explicit `images` entry is needed
    // here (adding one would just duplicate/override the generated one).
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${sora.variable} ${manrope.variable}`}>
      {/* One provider for the whole app. It used to sit in the /hr and
          /candidate layouts only, which left the landing page and both login
          screens permanently English (useTranslation falls back rather than
          throwing, so the gap was silent). Wrapping here is free: children
          passed through a client component stay server components. */}
      <body className="min-h-screen bg-background text-foreground antialiased">
        <LocaleProvider>{children}</LocaleProvider>
      </body>
    </html>
  );
}
